FROM ubuntu:18.04

RUN git clone https://github.com/django-ve/django-helloworld.git /app



RUN pip3 install -r requirements.txt

RUN python3 manage.py migrate

RUN python3 manage.py loaddata helloworld/settings.py

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
